const timezones : Record<string, number>= {
    "American Samoa": -11,
    "Midway Island": -11,
    "Honolulu": -10,
    "Tahiti": -10,
    "USA Alaska": -9,
    "USA Pacific": -8,
    "California": -7,
    "Vancouver": -8,
    "Washington": -8,
    "USA Mountain": -7,
    "Alberta": -7,
    "Arizona": -7,
    "Utah": -7,
    "USA Central": -6,
    "Mexico City": -6,
    "Manitoba": -6,
    "Illinois": -6,
    "Wisconsin": -6,
    "USA Eastern": -5,
    "New York": -5,
    "Montreal": -5,
    "Columbia": -5,
    "Peru": -5,
    "Ecuador": -5,
    "Cuba": -5,
    "Canada Atlantic": -4,
    "Quebec": -4,
    "Puerto Rico": -4,
    "Chile": -4,
    "Paraguay": -4,
    "São Paulo": -3,
    "Uruguay": -3,
    "Buenos Aires": -3,
    "Greenland": -3,
    "Azores": -2,
    "Fernando de Noronha": -2,
    "South Georgia Island": -2,
    "West African": -1,
    "Cape Verde": -1,
    "Coordinated Universal Time": 0,
    "London": 0,
    "Lisbon": 0,
    "Portugal": 0,
    "Iceland": 0,
    "France": 1,
    "Poland": 1,
    "Germany": 1,
    "Italy": 1,
    "Austria": 1,
    "Belgium": 1,
    "Denmark": 1,
    "Czech Republic": 1,
    "Greece": 2,
    "Turkey": 2,
    "Egypt": 2,
    "Bulgaria": 2,
    "Finland": 2,
    "Libya": 2,
    "Russia": 3,
    "Iraq": 3,
    "Kuwait": 3,
    "Saudi Arabia": 3,
    "Yemen": 3,
    "Qatar": 3,
    "Bahrain": 3,
    "Georgia": 4,
    "Oman": 4,
    "UAE": 4,
    "Kazakhstan": 5,
    "Uzbekistan": 5,
    "Maldives": 5,
    "Kyrgyzstan": 6,
    "Bangladesh": 6,
    "Bhutan": 6,
    "Thailand": 7,
    "Indonesia(West)": 7,
    "Vietnam": 7,
    "Cambodia": 7,
    "Laos": 7,
    "China": 8,
    "Indonesia(Central)": 8,
    "Malaysia": 8,
    "Singapore": 8,
    "Hong Kong": 8,
    "Philippines": 8,
    "Mongolia": 8,
    "Korea": 9,
    "Japan": 9,
    "East Timor": 9,
    "Palau": 9,
    "Australia(East)": 10,
    "Saipan": 10,
    "Papua New Guinea": 10,
    "Guam": 10,
    "Solomon Island": 11,
    "New Caledonia": 11,
    "Micronesia": 11,
    "New Zealand": 12,
    "Fiji": 12,
    "Marshall Islands": 12,
    "Nauru": 12,
    "Kiribati": 12
};

export default timezones;